"""empty message

Revision ID: 67ec35f14f1f
Revises: 
Create Date: 2022-04-17 18:12:07.593387

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '67ec35f14f1f'
down_revision = None
branch_labels = None
depends_on = None


def add_data(_op: op):
    brand_names = ('Apple', 'Google', 'Microsoft')
    for brand_name in brand_names:
        _op.execute(f"INSERT INTO brand (name) values ('{brand_name}')")
    for i in range(1, 4):
        _op.execute(f"INSERT INTO customer (login) values ('test_user_{i}')")
    for code in ("SDFJ93", "83DJAKQ"):
        _op.execute(f"INSERT INTO discount_code (code, brand_id, issued_to_user, used) values"
                    f" ('{code}', (SELECT id from brand limit 1), false, false)")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('customer',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('login', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('discount_code',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('code', sa.Text(), nullable=False),
                    sa.Column('issued_to_user', sa.Boolean(), nullable=True),
                    sa.Column('used', sa.Boolean(), nullable=True),
                    sa.Column('brand_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['customer.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    add_data(op)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discount_code')
    op.drop_table('customer')
    op.drop_table('brand')
    # ### end Alembic commands ###
